Projects, links, team are loaded from git
mild-blue/mild.blue pull request #8
Opened 2020-11-30 19:13 UTC by misslecter

2020-12-01 09:39 UTC, kubantjan commented
Jeste company veci se neloaduji z jsonu. udelal jsem task https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json​​​​​​​

2020-12-01 09:49 UTC, kubantjan commented on index.html
>        Meet our 6 member team.
jak moc je to tady hardcoded? slo by proste spocitat pocet clenu tymu v ty slozce a sem ukazat vsechny? jde mi o to, co se stane, kdyz pridat 7 clena?

2020-12-01 09:50 UTC, kubantjan commented
jeste byla posunuta do in review karticka, ktera vubec nebyla done: https://trello.com/c/54HWSExV/9-web-pridat-sekci-na-stranku-s-detailnejsim-popisem-spolecnosti tak jsem ji vratil :)

2020-12-01 09:57 UTC, kubantjan requested changes
Pripada mi to dobry, zda se ze textiky probublavaji, mrkni na my komentare akorat, spis jsou z toho dalsi tasky do budoucna

2020-12-01 10:10 UTC, kubantjan commented
Co je presne potreba udelat kdyz zmenim text v about aby ta zmena probublala sem? Staci proste pockat? Nebo je treba nejaka akce?

2020-12-01 11:04 UTC, misslecter commented
@kubantjan 

> Jeste company veci se neloaduji z jsonu. udelal jsem task [https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json​​​​​​​](https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)

> jeste byla posunuta do in review karticka, ktera vubec nebyla done: https://trello.com/c/54HWSExV/9-web-pridat-sekci-na-stranku-s-detailnejsim-popisem-spolecnosti tak jsem ji vratil :)

řešila bych to v jiném PR, ted se to týká pouze projektů, médií a týmu

> Co je presne potreba udelat kdyz zmenim text v about aby ta zmena probublala sem? Staci proste pockat? Nebo je treba nejaka akce?

web fetchne jsony z url a když se změní jejich obsah, změní se to i na stránkách, nic dalšího není potřeba :)
https://github.com/mild-blue/mild.blue/blob/7a9118ceebe390dad26a7af0fc3ff2386354892d/assets/js/services/ContentService.js#L33-L37

> jak moc je to tady hardcoded? slo by proste spocitat pocet clenu tymu v ty slozce a sem ukazat vsechny? jde mi o to, co se stane, kdyz pridam 7. clena? (Nebo dalsi projekt?)

Kdyby se přidal další člen, tak se na webu musí přidat jeho fotka v `assets/img/team` a `key` do tohoto seznamu:
https://github.com/mild-blue/mild.blue/blob/7a9118ceebe390dad26a7af0fc3ff2386354892d/assets/js/services/ContentService.js#L29

To číslo můžu nastavovat automaticky podle délky seznamu, to je pravda.

2020-12-01 11:56 UTC, kubantjan commented
> @kubantjan
> 
> > Jeste company veci se neloaduji z jsonu. udelal jsem task [https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json​​​​​​​](https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)
> 
> > jeste byla posunuta do in review karticka, ktera vubec nebyla done: https://trello.com/c/54HWSExV/9-web-pridat-sekci-na-stranku-s-detailnejsim-popisem-spolecnosti tak jsem ji vratil :)
> 
> řešila bych to v jiném PR, ted se to týká pouze projektů, médií a týmu
> 
> > Co je presne potreba udelat kdyz zmenim text v about aby ta zmena probublala sem? Staci proste pockat? Nebo je treba nejaka akce?
> 
> web fetchne jsony z url a když se změní jejich obsah, změní se to i na stránkách, nic dalšího není potřeba :)
> https://github.com/mild-blue/mild.blue/blob/7a9118ceebe390dad26a7af0fc3ff2386354892d/assets/js/services/ContentService.js#L33-L37
> 
> > jak moc je to tady hardcoded? slo by proste spocitat pocet clenu tymu v ty slozce a sem ukazat vsechny? jde mi o to, co se stane, kdyz pridam 7. clena? (Nebo dalsi projekt?)
> 
> Kdyby se přidal další člen, tak se na webu musí přidat jeho fotka v `assets/img/team` a `key` do tohoto seznamu:
> https://github.com/mild-blue/mild.blue/blob/7a9118ceebe390dad26a7af0fc3ff2386354892d/assets/js/services/ContentService.js#L29
> 
> To číslo můžu nastavovat automaticky podle délky seznamu, to je pravda.

Hmm takze bychom meli do toho repa about pridat i obrazky nas vlastne. Nahrajes je tam prosim? At tyhle veci mame taky na jednom miste. Navic fotky se obecne budou hodit i jindy.

> @kubantjan
> 
> > Jeste company veci se neloaduji z jsonu. udelal jsem task [https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json​​​​​​​](https://trello.com/c/EJvQ8fpA/19-load-company-desc-also-from-json%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)
> 
> > jeste byla posunuta do in review karticka, ktera vubec nebyla done: https://trello.com/c/54HWSExV/9-web-pridat-sekci-na-stranku-s-detailnejsim-popisem-spolecnosti tak jsem ji vratil :)
> 
> řešila bych to v jiném PR, ted se to týká pouze projektů, médií a týmu
> 
> > Co je presne potreba udelat kdyz zmenim text v about aby ta zmena probublala sem? Staci proste pockat? Nebo je treba nejaka akce?
> 
> web fetchne jsony z url a když se změní jejich obsah, změní se to i na stránkách, nic dalšího není potřeba :)
> https://github.com/mild-blue/mild.blue/blob/7a9118ceebe390dad26a7af0fc3ff2386354892d/assets/js/services/ContentService.js#L33-L37
> 
> > jak moc je to tady hardcoded? slo by proste spocitat pocet clenu tymu v ty slozce a sem ukazat vsechny? jde mi o to, co se stane, kdyz pridam 7. clena? (Nebo dalsi projekt?)
> 
> Kdyby se přidal další člen, tak se na webu musí přidat jeho fotka v `assets/img/team` a `key` do tohoto seznamu:
> https://github.com/mild-blue/mild.blue/blob/7a9118ceebe390dad26a7af0fc3ff2386354892d/assets/js/services/ContentService.js#L29
> 
> To číslo můžu nastavovat automaticky podle délky seznamu, to je pravda.


JJ ty veci resme jinym PR.

jinak cool s tema text zmenama :+1: 

Fotky jsem hodil sem: https://github.com/mild-blue/about/tree/master/people/photos

tak je muzes loadovat pak tam odsud at to mame vsechno na jednom miste. (bud to udelej tady, nebo si prosim udelej task, at na to nezapomeneme a mame to ted uklizeny dik.)

predpokladam ze teda projekty i clenove tymu se teda upravuji jen tak, ze pridam cloveka. nebo projektu do nejakyho listu. pridal jsem JSON do about abychom to uz tam meli vsechno (bylo tam typo v kidney, tak to jsem fixnul taky):

https://github.com/mild-blue/about/blob/master/people/people_list.json
https://github.com/mild-blue/about/blob/master/projects/project_list.json
https://github.com/mild-blue/about/blob/master/written_about_us/source_list.json

Zas klidne res v dalsim PR, pokud uz je toho moc

2020-12-01 12:30 UTC, misslecter commented
@kubantjan Tak jo, tedka by web nemel vedet nic o konretnich clenech tymu, projektech a mediich, vse leze z gitu :)

2020-12-01 21:35 UTC, kubantjan approved these changes
lgtm. asi klidne merguj

2020-12-03 13:28 UTC, LukasForst requested changes

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Links.js
> +    console.log('Loaded links', links);
zadna konzole do produkce pls, bud si zmen prototype u konzole, tak ze to vyprinti, kdyz window ref neni `mild.blue` nebo to smaz

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Links.js
> +    return `<a href="${link.url}" target="_blank" class="links-item hidden">
tady bych to `<a` fouknul na novou radku kvuli formatovani

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Projects.js
> +    console.log('Loaded projects', projects);
zadna konzole

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Team.js
> +    console.log('Loaded team', members);
konzole

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Links.js
> +      for (let l of currentLinks) {
`const` by neslo?

2020-12-03 13:28 UTC, LukasForst commented on assets/js/services/ContentService.js
> +    if (projects && projects[projectsKey]) {
mozna check ze res je teda skutecne ten dict? pripadne v tom then rovnou nekde vypsat chybu, kdyz nam github nevrati 200?

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Links.js
> +    const maxHeight = Math.max(...Array.from(renderedLinks).map(l => l.offsetHeight));
je rozdil mezi `Array.from` a `[]`? pokud ne, pouzil bych `[]`

2020-12-03 13:28 UTC, LukasForst commented on assets/js/services/ContentService.js
> +    responses = responses.filter(response => response.status === 200); // filter unsuccessful responses
tohle cely se neda zachainovat pres `then`?

2020-12-03 13:28 UTC, LukasForst commented on assets/js/classes/Links.js
> +    $(this.linksContainer).owlCarousel(this.carouselOptions);
a to ze prej nechceme pouzivat jQuery 😆

2020-12-03 15:15 UTC, misslecter commented on assets/js/classes/Links.js
> +    $(this.linksContainer).owlCarousel(this.carouselOptions);
to knihovna na carousel je jQuery bohužel 🤮 na custom kod je jQuery zbytečnýýýýýý

2020-12-03 15:42 UTC, misslecter commented on assets/js/services/ContentService.js
> +    if (projects && projects[projectsKey]) {
V `projects` máš učitě objekt, a to buď `Response` anebo výsledek `.json()`:
```
.then(res => res.status === 200 ? res.json() : res)
```
Přijde mi že kontrola na `null` a `undefined`, a další na existenci potřebného klíče v objektu, by měla stačit.

Můžem přidat `else` s `console.error`, že ty `projects` jsou nějaké vadné.

2020-12-03 15:52 UTC, misslecter commented on assets/js/classes/Links.js
> +    const maxHeight = Math.max(...Array.from(renderedLinks).map(l => l.offsetHeight));
Pak tam musí být `...[...` 😆 
```
Math.max(...[...renderedLinks].map(l => l.offsetHeight));
```

2020-12-03 15:53 UTC, misslecter commented on assets/js/services/ContentService.js
> +    responses = responses.filter(response => response.status === 200); // filter unsuccessful responses
dá, ale je to pak dlouhý ošklivý chain který dělá až moc věcí

2020-12-03 15:55 UTC, misslecter commented on assets/js/classes/Links.js
> +    const maxHeight = Math.max(...Array.from(renderedLinks).map(l => l.offsetHeight));
A je to rozdíl https://stackoverflow.com/questions/931872/what-s-the-difference-between-array-and-while-declaring-a-javascript-ar

2020-12-03 16:22 UTC, LukasForst commented on assets/js/classes/Links.js
> +    const maxHeight = Math.max(...Array.from(renderedLinks).map(l => l.offsetHeight));
och, okej, nechme takhle

2020-12-03 16:25 UTC, LukasForst commented on assets/js/services/ContentService.js
> +    if (projects && projects[projectsKey]) {
ok, tak to nechme

2020-12-04 19:26 UTC, LukasForst approved these changes

2020-12-05 09:55 UTC, merged